### ISSUE TITLE
Some bitmaps in the PDF export

### ISSUE THREAD

**Issue by meadows19** [muktyas/quranmuks#2]
If you look at the PDF file for Juz 29, for example, there are some words that are exported in raster/bitmap format in the PDF.

For example:
1) The first line of Surah Noon, page 564
2) The 4th line on page 568
3) Part of the third last line in Surah Qiyamah, page 578 (Screenshot attached) 
![page578 screenshot](https://user-images.githubusercontent.com/21014471/82948147-ea744800-9fa9-11ea-8c04-e0bf8964a81e.png)

4) Two words on the 4th last line on page 581

I tried exporting again from the ODT file, using Microsoft Word, and my own generated PDF has the same problem. The same words are exported in raster/bitmap instead of vector. 

I don't know why this problem exists, and why it is only for these specific words. You can find this same problem in the PDF files for other Juz also.

**Comment by muktyas** [comment]
Yes.. I think it is on the font file problem (otf).
But if we zoom it (in libreoffice, I copy that words into new document and make the font size 999), it still doesn't look broken and still good.
I'm sorry @meadows19, until now, I don't know how to fix it.
