### ISSUE TITLE
Last ayah in Surah Jumuah (28th Juz)

### ISSUE THREAD

**Issue by meadows19** [muktyas/quranmuks#3]
Assalamu Alaykum,

Please look at the last ayah in Surah Jumuah.

In the Majidi script, the _waw_ should have a single _fatha_ (not a _fathatain_) and the small _noon_ should have a _kasra_.

Like this:
![Mushaf](https://user-images.githubusercontent.com/21014471/112115869-bae29c00-8bca-11eb-9d38-9f2296bb2eb4.png)

However, in this font, they forgot to remove the extra _fatha_ on the _waw_, and forgot to put the extra _kasra_ on the small _noon_.

Like this:
![Juzz 28](https://user-images.githubusercontent.com/21014471/112116557-76a3cb80-8bcb-11eb-9906-a5e2a5503566.png)

That means you can't read it unless you know from before how to pronounce it.

**Comment by muktyas** [comment]
Wa 'alaikumussalaam wa rahmatullaah wa barakaatuh.
Thank You, @meadows19. But in indonesian quran, it is right. Like this:
![au lahwaning fadhdhu](https://user-images.githubusercontent.com/13088121/171245744-0889980d-263e-4bee-9a2a-b39a30defc83.png)
It reads: "au lahwaning fadhdhuu..". Sometimes the "nun wiqayah" has kasrah, and sometimes it doesn't, but it reads "kasrah".
We can read it directly from quran kemenag site here:
[https://quran.kemenag.go.id/sura/62](https://quran.kemenag.go.id/sura/62)
It is the official website of the Ministry of Religion of the Republic of Indonesia.
