### ISSUE TITLE
Ayah 60 in Surah Hajj

### ISSUE THREAD

**Issue by meadows19** [muktyas/quranmuks#4]
Assalamu Alaykum
Ayah 60 in Surah Hajj has an extra word (bihi) added by mistake. 17th juz file, both the odt and pdf.

**Comment by muktyas** [comment]
Wa 'alaykumussalaam wa rahmatullaah wa barakaatuh.
Jazakallah khair, @meadows19.

Fix: QS. Al Hajj:60. remove extra 'bihi'.
