### ISSUE TITLE
List of customizations?

### ISSUE THREAD

**Issue by meadows19** [muktyas/quranmuks#5]
Assalamu Alaykum,

Can you please make a list of customizations that are used?

These are the ones I found so far:

1) Juz 4, Surah Nisa, Ayah 19, page 80, kasra added to word 'bifahishatin'
2) Juz 8, Surah Araaf, Ayah 84, page 160, shadda covered in word 'min'

Are there any others?
Thank you very much.

**Comment by muktyas** [comment]
Wa 'alaikumussalaam wa rahmatullaah wa barakaatuh.
Thank you very much, @meadows19.. I wrote down the list of some corrected notes in the Catatan.txt file.
