### ISSUE TITLE
Surah Fussilat (Surah 41) is incorrectly labelled

### ISSUE THREAD

**Issue by meadows19** [muktyas/quranmuks#6]
Assalamu Alaykum.
Surah Fussilat (Surah 41) is incorrectly labelled (in the Surah heading) as Surah Qasas, in both the ODT and the PDF.

**Comment by muktyas** [comment]
Wa 'alaikumussalaam wa rahmatullaah wa barakaatuh.
Thank you, @meadows19.. Jazakallah khair.

Now, it is fixed.
